### ISSUE TITLE
Annualization argument in capture methods

### ISSUE THREAD

**Issue by rubenbriones** [stefan-jansen/empyrical-reloaded#21]
Hello,

Would it be possible to add the `annualization` argument to the capture (`capture`, `up_capture`, `down_capture`) functions in stats module?

Thanks in advance.

**Comment by MBounouar** [comment]
I am not sure I understand your issue, the functions have the period argument that defines the periodicity of the returns. I agree thought that the documentation is confusing. Could you provide an example ?

**Comment by rubenbriones** [comment]
But `annuzalization` parameter have the same purpose as the `period` parameter, right? I just would like to pass a custom `annualization` (int) factor, that is not supported by the `period` (str) paramater. For example for calculating the capture for a hourly returns timeseries.

**Comment by stefan-jansen** [comment]
Hi @rubenbriones, pull requests are always welcome!
