### ISSUE TITLE
test_beta_fragility_heuristic fails, probably numpy2 issue

### ISSUE THREAD

**Issue by amdupre** [stefan-jansen/empyrical-reloaded#34]
Environment:
macOS Sonoma 14.5, installed via pip

ran simple "pytest tests" and 

test passes on Python 3.9 with:
[requirements_passes.txt](https://github.com/user-attachments/files/16444279/requirements_passes.txt)

test fails on Python 3.11 with:
[requirements_fails.txt](https://github.com/user-attachments/files/16444278/requirements_fails.txt)

I think it is just line 1074 in test_stats.py, if I remove:
            ("mixed_returns", "simple_benchmark", 0.09),

it passes.  Haven't had time to look further, though.

**Comment by stefan-jansen** [comment]
Should be addressed by #36
